import "unknwn.idl";

[object, uuid(261c74a7-272a-45d2-b472-2c8d1f6de631), helpstring("WebAssembly COM interface")]
interface IWebAssemblyCOM : IUnknown
{
	HRESULT AddWasiEnv([in] LPSTR Key, [in] LPSTR Value);
	HRESULT AddWasiDir([in] LPSTR Dir);
	HRESULT SetStackSize([in] int Size);
	HRESULT SetHeapSize([in] int Size);
	HRESULT Open([in] LPSTR FilePath);
	HRESULT Exec();
	[local] HRESULT CallFunc([in] LPSTR FuncName, [in] LPVOID pArgs, [out, retval] LPVOID *pResult);
	HRESULT Close();
};

[uuid(f373d9ea-1e49-4831-9753-a092c6a326ee), helpstring("WebAssembly COM interface")]
library WebAssemblyCOM
{
    importlib("stdole32.tlb");
    importlib("stdole2.tlb");

    interface IWebAssemblyCOM;
}
